version: '3'
services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"

  web:
    build: server
    restart: always
    depends_on:
      - "db"
    environment:
      POSTGRES_URI: ${POSTGRES_URI}
    ports:
      - "8080:8080"
