version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: make server-image-build
  deploy:
    machine: true
    steps:
      - checkout
      - run: make deploy
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build
