version: 2
jobs:
  db:
    docker:
      - image: circleci/python:3.6-browsers
    steps:
      - checkout
      - run:
          command: |
            pip install --user yandex-pgmigrate
            PATH=$PATH:~/.local/bin
            make migrate
  node:
    docker:
      - image: circleci/python:3.6-browsers
    working_directory: ~/memcool/node
    steps:
      - checkout:
          path: ~/memcool
      - restore_cache:
          key: py-{{ checksum "requirements.txt"}}          
      - run: pip install --user -r requirements.txt
      - save_cache:
          paths:
            - ~/.cache/pip
          key: py-{{ checksum "requirements.txt" }}
      - run: 
          command: |
            PATH=$PATH:~/.local/bin
            pylint mempush.py
  build:
    machine: true
    steps:
      - checkout
      - run: make server-image-build
  deploy:
    machine: true
    steps:
      - checkout
      - run: make deploy
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - node
      - build
      - db:
          requires:
            - build
      - deploy:
          requires:
            - db
