version: 2
jobs:
  db:
    docker:
      - image: circleci/python:3.6-browsers
    steps:
      - checkout
      - run:
          command: |
            pip install --user yandex-pgmigrate
            PATH=$PATH:~/.local/bin
            make migrate
  node:
    docker:
      - image: circleci/python:3.6-browsers
    working_directory: ~/bitkit/node
    steps:
      - checkout:
          path: ~/bitkit
      - restore_cache:
          key: py-{{ checksum "requirements.txt"}}          
      - run: pip install --user -r requirements.txt
      - save_cache:
          paths:
            - ~/.cache/pip
          key: py-{{ checksum "requirements.txt" }}
      - run: 
          command: |
            PATH=$PATH:~/.local/bin
            pylint mempush.py
  build:
    docker: 
      - image: circleci/golang:1.8.7
    steps:
      - checkout
      - run: mkdir -p /tmp/workspace
      - run: mkdir -p "$HOME/go/src"
      - run: ln -s $(pwd)/server "$HOME/go/src/server"
      - run: cd server && go get -d -v ./...
      - run: make build
      - run: mv deployment.zip /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - deployment.zip
  deploy:
    docker:
      - image: circleci/python:3.6-browsers
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run: |
          if [-e /tmp/workspace/deployment.zip]
          then
            echo "ok"
          else
            echo "not ok"
          fi
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - node
      - build
      - db:
          requires:
            - build
      - deploy:
          requires:
            - db
